name: Correcting Hangman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.3.1
      
      - name: Download the marking package
        run: |
          python -m pip install --upgrade pip
          pip install hangman-marking-aicore

      - name: Verify milestone 1 tasks
        run: |
          python -m unittest -v hangman_test.test_milestone1 2> milestone_1.txt
          python hangman_test.verify_milestone1.py
